### ISSUE TITLE
do coarse-fine interpolation for ghost cells with internal energy

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#102]
To avoid temperature glitches, it is necessary to interpolate at coarse-fine boundaries with the primitive variables when filling the ghost cells in the hydro update.

This could be accomplished by creating a temporary multifab with the primitive variables, then performing the ghost cell exchange with it. This would increase GPU memory usage significantly, since primitive variable multifabs would be needed to be stored for every AMR level.

**Comment by BenWibking** [comment]
@markkrumholz how is this done in ORION?

**Comment by markkrumholz** [comment]
ORION doesn't permanently store multifabs of primitive variables. Instead, the procedure is that, right before the copy operation is peformed on any FAB, the current total energy is copied into a temporary, and the total energy field in the FAB is overwritten by placing the internal energy into it. Then after the copy/fill step, the temporary is copied back into the total eneryg field. Thus you only need to store a temporary for one FAB at a time, and just for a single variable. That makes the memory overhead small.

**Comment by BenWibking** [comment]
Ah, I see. I think we can do this with the `pre_interp` and `post_interp` callback functions: https://github.com/AMReX-Codes/amrex/blob/103db6ebe2b570910ac4dbd7d6611e59d80f1a0b/Src/AmrCore/AMReX_FillPatchUtil_I.H#L548

See also: https://github.com/AMReX-Codes/amrex/commit/ac6d7b00245ba7746af8fe9cdda68fb75b80ab96

**Comment by BenWibking** [comment]
@markkrumholz is there a problem where this is known to make a difference? My implementation (if it's working right, anyway) doesn't seem to make such of a difference for the shock-cloud problem.
