### ISSUE TITLE
Make EOS consistent between hydro and chemistry

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#271]
In simulations with hydro+chemistry, we should use the same EOS for hydro and chemistry. This is currently not the case. For primordial chem, we are using the EOS in Microphysics whereas for hydro we are using the one in Quokka Physics Traits.

**Comment by BenWibking** [comment]
Do you want to work on this? I think the solution is to just use the Microphysics EOS, since that's now included in Quokka.

**Comment by psharda** [comment]
Yes I can give it a try. It will anyway need to be done before I can do a Pop III sim with quokka. Let's come back to this after the species flux conservation stuff.

**Comment by psharda** [comment]
> Do you want to work on this? I think the solution is to just use the Microphysics EOS, since that's now included in Quokka.

Coming back to this @BenWibking, the changes we would need to make would be wherever hydro calls the EOS. How do we do this? Do we just add `#ifdef PRIMORDIAL_CHEM` in such places? Or, do we insert a new template function in `EOS.hpp`

**Comment by BenWibking** [comment]
> > Do you want to work on this? I think the solution is to just use the Microphysics EOS, since that's now included in Quokka.
> 
> Coming back to this @BenWibking, the changes we would need to make would be wherever hydro calls the EOS. How do we do this? Do we just add `#ifdef PRIMORDIAL_CHEM` in such places? Or, do we insert a new template function in `EOS.hpp`

No, please do not do that. `ifdef` should only be used as a last resort to avoid excessively long build times.

I think the solution is to either replace the internals of `quokka::EOS` with calls to Microphysics EOS functions, or remove `quokka::EOS` entirely and replace all of its uses with calls to Microphysics EOS functions.

**Comment by psharda** [comment]
Can you check the file changes in #280? I used ifdefs which you can ignore, but the logic of using Microphysics in the internals of `quokka::EOS` is there now. 

If we want to replace all the EOS stuff in Quokka with calls to Microphysics, that would require building Microphysics with multiple EOS at the same time (currently we only build the Microphysics EOS for primordial chem). I do not know how this would work, as calling `eos(eos_input_rt, state)` as we do now only points to one specific implementation of the EOS.

Instead of `#ifdef` maybe we can use the `is_chemistry_enabled` boolean? Would that avoid large compile times?

**Comment by BenWibking** [comment]
> If we want to replace all the EOS stuff in Quokka with calls to Microphysics, that would require building Microphysics with multiple EOS at the same time (currently we only build the Microphysics EOS for primordial chem). I do not know how this would work, as calling `eos(eos_input_rt, state)` as we do now only points to one specific implementation of the EOS.

I think the solution is to just call the Microphysics `eos` function in all cases. I don't think it's necessary to build Microphysics with multiple EOSes, but we do need the ability to build Microphysics with a constant-gamma EOS if chemistry is disabled. Which EOS is built should be chosen individually by each problem, or otherwise set for each problem automatically based on which chemistry network is selected (and defaults to constant-gamma if no network is used).

**Comment by psharda** [comment]
> > If we want to replace all the EOS stuff in Quokka with calls to Microphysics, that would require building Microphysics with multiple EOS at the same time (currently we only build the Microphysics EOS for primordial chem). I do not know how this would work, as calling `eos(eos_input_rt, state)` as we do now only points to one specific implementation of the EOS.
> 
> I think the solution is to just call the Microphysics `eos` function in all cases. I don't think it's necessary to build Microphysics with multiple EOSes, but we do need the ability to build Microphysics with a constant-gamma EOS if chemistry is disabled. Which EOS is built should be chosen individually by each problem, or otherwise set for each problem automatically based on which chemistry network is selected (and defaults to constant-gamma if no network is used).

Okay, then that means we should change the way we build Microphysics with CMake, as it currently only builds for primordial chem EOS. Microphysics has a `gamma_law` EOS in it already. 

I see that in some places Quokka would also need to know the mean molecular weight and gamma. Microphysics stores the mean molecular weight in its `burn_t state` object but I don't think it stores gamma. I have just asked Mike about that.

**Comment by BenWibking** [comment]
Everywhere $\gamma$ is used, it should be replaced with a call to a more general EOS function. The adiabatic index itself should almost never be used directly.

**Comment by BenWibking** [comment]
With general EOSes, the convention is usually to directly compute and use thermodynamic derivatives. These can be expressed in terms of various dimensionless parameters (including $\gamma$), but usually the thermodynamics derivatives are what is needed. For the full details, you can read, e.g.: https://ui.adsabs.harvard.edu/abs/1989RvMP...61...75M/abstract

**Comment by psharda** [comment]
Microphysics calculates and stores `c_v` in `burn_t` but not `c_p`. It stores both in a different struct `eos_state`. So maybe we can use `eos_state` to access `eos_state.cp` and `eos_state.cv` and then calculate $\gamma$ from it

**Comment by BenWibking** [comment]
No, you cannot do this. See this paragraph on page 79 of the earlier reference: "the adiabatic exponent $\gamma$ is not the ratio of specific heats $\gamma_0$ for a general EOS. In fact, Eq. (2.12) shows that $C_P/C_V = \gamma g / (\gamma g - \Gamma^2)$."

**Comment by BenWibking** [comment]
You can see which thermodynamic derivatives are needed here: https://github.com/quokka-astro/quokka/issues/278

**Comment by psharda** [comment]
Okay. But the first step we have to figure out is building Microphysics in Quokka with > 1 EOS, or, the test problem in quokka specifies which EOS to build Microphysics with. How do we handle CMakeLists in Microphysics and Quokka to do either of the two options?

**Comment by BenWibking** [comment]
I think we have to have a CMake option for which network to use. Perhaps we can use the `null` network when we don't want chemistry and just want a gamma-law EOS? Need to ask Mike.

**Comment by psharda** [comment]
Yeah. The other file we need to build is `extern_parameters.cpp/.H`, which we build during the configuration stage. How do we create a CMake option for Quokka test problems to build one or the other EOS in Microphysics during this stage? Do we move the Microphysics build from `quokka/CMakeLists.txt` to each test within `quokka/src/Test/CMakeLists.txt`?

**Comment by BenWibking** [comment]
I would use a CMake variable.

**Comment by psharda** [comment]
Can you expand on it? Are you thinking of adding a CMake variable like `BUILD_UNIT_TEST` that we use in Microphysics, and using one of the `target_compile_` in Quokka tests?

**Comment by BenWibking** [comment]
What I have in mind is adding a variable that is a string (instead of a boolean ON/OFF) that points to the network directory. This just changes all of the paths to point to that subdirectory instead of the primordial_chem directory. I think this should be set from the Quokka CMakeLists.txt, and then somehow propagated to the Microphysics CMakeLists.txt. Or maybe it can just be defined from the latter, since that's how AMReX creates build options like `AMReX_SPACEDIM`, etc.

**Comment by psharda** [comment]
But I don't understand how this will work when building all the Quokka tests (which require different EOS setups) at the same time? Do we build separate versions of Microphysics (based on the EOS needed) for each Quokka test? For example, for HydroShocktube, we build Microphysics with gamma-law EOS (the scope of which is just this test directory). But for PrimordialChem, we build Microphysics with primordial_chem EOS?

**Comment by BenWibking** [comment]
Yes. It already works this way, except it's currently primordial_chem or nothing.

**Comment by BenWibking** [comment]
Microphysics isn't really a separate build. It's just a bunch of header files and *.cpp files that are also included in each test problem. The separate libMicrophysics build doesn't actually do anything, since we realized that we might need a different network for each problem and switched to just including all the Microphysics source files within `add_executable` for each Quokka test problem.

**Comment by psharda** [comment]
Okay, first step done. I can now build Microphysics with the primordial chem EOS for the primordial chem test, and gamma_law EOS for other tests. Now, we need to look into the gamma_law EOS in Microphysics

**Comment by psharda** [comment]
Encountered an issue: while compiling other (non-chemistry) tests, we have to include `RadhydroSimulation.hpp`. This file in turn includes `Chemistry.hpp`, which barfs if the EOS+network compiled via Microphysics does not have the variables it uses. 

For example, `Chemistry.hpp` uses the variable `spmasses` defined in `extern_parameters.H` in PrimordialChem. This variable is not defined in `extern_parameters.H` in HydroShocktubeCMA (now, every test problem will have its own `extern_parameters.H`). So, when `Chemistry.hpp` is compiled while compiling HydroShocktubeCMA test, it throws errors.

My simple fix is to wrap up `#include Chemistry.hpp` in `RadhydroSimulation.hpp` with `#ifdef PRIMORDIAL_CHEM` around it so that `Chemistry.hpp` is only compiled with PrimordialChem. Do you have a better solution?

**Comment by BenWibking** [comment]
> My simple fix is to wrap up `#include Chemistry.hpp` in `RadhydroSimulation.hpp` with `#ifdef PRIMORDIAL_CHEM` around it so that `Chemistry.hpp` is only compiled with PrimordialChem. Do you have a better solution?

I think it would be slightly better to put the ifdef in Chemistry.hpp itself. Perhaps make it `#ifdef CHEMISTRY` rather than specific to primordial chemistry, since `spmasses` should be defined for any non-empty network.

**Comment by psharda** [comment]
Resolved by #338
