### ISSUE TITLE
Unable to read in Checkpoints in Setonix GPUs

### ISSUE THREAD

**Issue by aditivijayan** [quokka-astro/quokka#300]
On Setonix GPUs, runs without AMR compiled in RELEASE mode produce bad checkpoints that are not readable by subsequent re-runs. When I try to read in these bad checkpoints, the code crashes with an  std::runtime error ( what():  Read of Vector<Vector<Real>> failed). 

A bad checkpoint contains nans in the chkNNNNN/Level_0/Cell_H file and the number of nans in the checkpoint increases with the number of time steps taken to produce that checkpoint. The number of nans in a checkpoint also depends on the number of GPUs used. 

The issue is fixed if the code is compiled in the debug mode. Another workaround is to trick the code into thinking it is an AMR run when it is actually not by implementing an impossible to satisfy refinement criterion.

**Comment by BenWibking** [comment]
@aditivijayan Is this still an issue after the GPU driver upgrade?

**Comment by BenWibking** [comment]
Fixed by GPU driver upgrade to version 5.18.13 (ROCm 5.4.5) by Pawsey staff.
