### ISSUE TITLE
-lstdc++fs link issues on Setonix

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#313]
We need to conditionally link against `stdc++fs` on Setonix, since sometimes it exists and we need to link against it and sometimes it's not needed, depending on which compilers/modules we are using.

CMake bug report: https://gitlab.kitware.com/cmake/cmake/-/issues/17834.

cc @psharda

**Comment by BenWibking** [comment]
This may be the best existing solution: https://github.com/lethal-guitar/RigelEngine/blob/master/cmake/Modules/FindFilesystem.cmake

**Comment by BenWibking** [comment]
@psharda I think this issue is coming from the Microphysics build. It goes away if I patch Microphysics/CMakeLists.txt following the changes that I posted in the other PR.

**Comment by psharda** [comment]
So are you saying `QuokkaObj` did not break this linking, and it was the Microphysics build?

**Comment by BenWibking** [comment]
No, both things broke the build, but in different ways.

**Comment by BenWibking** [comment]
Fixed by https://github.com/AMReX-Astro/Microphysics/pull/1217.
