### ISSUE TITLE
turn object library into a static library?

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#315]
If it is possible turn `QuokkaObj` into a static library, it should avoid the linking issues that are causing the build to fail on Setonix: https://github.com/quokka-astro/quokka/issues/309.

**Comment by psharda** [comment]
I think the reason I opted for OBJECT instead of STATIC was that it wouldn't build on GPUs. But, this was before I was using `setup_target_for_cuda_compilation`. Let's see if #316 fixes this, and also builds QuokkaObj as a STATIC library successfully on GPUs
