### ISSUE TITLE
compute Roe-average sound speed for a general EOS

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#337]
To support a general EOS, this line in the Riemann solver must be changed:
https://github.com/quokka-astro/quokka/blob/aa288b57d2dda961815af7f986ebbb8fc30b9234/src/HLLC.hpp#L39

so that it matches Eq. 4.12 of Kershaw et al. (1998):

<img width="393" alt="Screenshot 2023-07-30 at 4 01 38 PM" src="https://github.com/quokka-astro/quokka/assets/1781919/cdc2d8cf-4904-4263-a6b2-83a884b46774">

For an ideal gas, $C_{P}^{\star} = 1/(\gamma - 1)$ and $C_{\rho}^{\star} = 0$.

For a general EOS, the calculation of $C_{\rho}^{\star}$ and $C_{P}^{\star}$ is nontrivial.

An algorithm to calculate these quantities is given here: [Appendix_A.pdf](https://github.com/quokka-astro/quokka/files/12210059/Appendix_A.pdf). (In their notation, $I$ is the specific internal energy (i.e., $e_{int}$).)

**Comment by BenWibking** [comment]
The end result is that we need these thermodynamic derivatives:
<img width="281" alt="Screenshot 2023-07-30 at 4 31 43 PM" src="https://github.com/quokka-astro/quokka/assets/1781919/cf6f82c3-99ac-4489-873d-ca4380312ff3">

**Comment by psharda** [comment]
For primordial chemistry, we need the ideal gas $c*^2$, right?

**Comment by BenWibking** [comment]
> For primordial chemistry, we need the ideal gas c∗2, right?

No, it's not the same as an ideal gas for primordial chemistry, because $\gamma$ is not constant.

If you implement the appropriate derivatives in each EOS, then you don't need to have an if statement to do something different for an ideal gas EOS vs some other EOS. You can just evaluate $C_{\rho}^{\star}$ and $C_{P}^{\star}$ and it will just give the right answer.

**Comment by psharda** [comment]
> > For primordial chemistry, we need the ideal gas c∗2, right?
> 
> No, it's not the same as an ideal gas for primordial chemistry, because γ is not constant.

Okay. Just out of curiosity, would it not work if we just pass the right $\gamma$ to HLLC.hpp at every step, by calling Microphysics and making it return a gamma given a composition?

**Comment by psharda** [comment]
> The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">

Solving the first equation, I get:

$C^*_{\rho} = \frac{1}{2(\gamma-1)} \left(\frac{\partial P^-}{\partial \rho^-} + \frac{\partial P^+}{\partial \rho^+}\right)$.

but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?

**Comment by BenWibking** [comment]
> > > For primordial chemistry, we need the ideal gas c∗2, right?
> > 
> > 
> > No, it's not the same as an ideal gas for primordial chemistry, because γ is not constant.
> 
> Okay. Just out of curiosity, would it not work if we just pass the right γ to HLLC.hpp at every step, by calling Microphysics and making it return a gamma given a composition?

No, because `\gamma` changes throughout the wave structure that the Riemann solver is solving.

**Comment by psharda** [comment]
> > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> 
> Solving the first equation, I get:
> 
> Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> 
> but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?

I wonder if I can assume the general EOS is variable separable, so, $P = F(\rho) \times G(I) \times C$, where $C$ is a constant and $F$ and $G$ are functions of density and eint

**Comment by markkrumholz** [comment]
To add a bit to Ben's comment: yes, in principle one could hold gamma fixed, do hydro, then go back and update gamma. However, the penalty for doing this is that effectively you are operator-splitting the update, so that you drop to first order accuracy in time.

**Comment by BenWibking** [comment]
> > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> 
> Solving the first equation, I get:
> 
> Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> 
> but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?

You can use the product rule:

$C^*_{\rho} \approx \frac{1}{2} (I^{-} + \rho^{-} \frac{\partial I^{-}}{\partial \rho^{-}} + I^{+} + \rho^{+} \frac{\partial I^{+}}{\partial\rho^{+}})$.

**Comment by psharda** [comment]
> > > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> > 
> > 
> > Solving the first equation, I get:
> > Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> > but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?
> 
> You can use the product rule:
> 
> Cρ∗≈12(I−+ρ−δI−δρ−+I++ρ+δI+δρ+).

Yes, that's what I used. But, after that, how do I find $\partial I / \partial \rho$, for a general EOS? For ideal-gas, I get the equation I wrote above.

**Comment by BenWibking** [comment]
> > > > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> > > 
> > > 
> > > Solving the first equation, I get:
> > > Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> > > but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?
> > 
> > 
> > You can use the product rule:
> > Cρ∗≈12(I−+ρ−δI−δρ−+I++ρ+δI+δρ+).
> 
> Yes, that's what I used. But, after that, how do I find ∂I/∂ρ, for a general EOS? For ideal-gas, I get the equation I wrote above.

You have to call the EOS to have it compute ∂I/∂ρ == $\partial e_{int} / \partial \rho$. It's just a thermodynamic derivative the EOS has to know (or an equivalent derivative obtainable via some thermodynamic identity).

**Comment by psharda** [comment]
ah I see.

**Comment by BenWibking** [comment]
> > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> 
> Solving the first equation, I get:
> 
> Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> 
> but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?

I'm not sure how you got this. $\partial e_{int} / \partial \rho$ for an ideal gas (assuming constant mean molecular weight) is always zero:

$\partial e_{int} / \partial \rho = \frac{\partial}{\partial \rho} ( \frac{1}{\gamma - 1} \frac{kT}{\mu}) = 0$

**Comment by psharda** [comment]
> > > The end result is that we need these thermodynamic derivatives: <img alt="Screenshot 2023-07-30 at 4 31 43 PM" width="281" src="https://user-images.githubusercontent.com/1781919/257074927-cf6f82c3-99ac-4489-873d-ca4380312ff3.png">
> > 
> > 
> > Solving the first equation, I get:
> > Cρ∗=12(γ−1)(∂P−∂ρ−+∂P+∂ρ+).
> > but here I assumed the ideal gas EOS between pressure and eint, and we don't want that. So we shouldn't use this equation right?
> 
> I'm not sure how you got this. ∂eint/∂ρ for an ideal gas (assuming constant mean molecular weight) is always zero:
> 
> ∂eint/∂ρ=∂∂ρ(1γ−1kTμ)=0

Yes, so if you solve the equation I got further, you will also get $\partial e_{int} / \partial \rho$, which is 0 as you say.

**Comment by BenWibking** [comment]
> Yes, so if you solve the equation I got further, you will also get ∂eint/∂ρ, which is 0 as you say.

sorry, I see that now.

**Comment by psharda** [comment]
Resolved by #338
