### ISSUE TITLE
Save gravitational potential in plotfiles

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#357]
We should have the ability to calculate gravitational potential and store it as a derived field in quokka snapshots.

**Comment by BenWibking** [comment]
Just for reference, the gravity solver is here: https://github.com/quokka-astro/quokka/blob/1b5d55dc15b46b56cc4722543230db32aa42c97f/src/simulation.hpp#L806

**Comment by psharda** [comment]
So, I see that there is a function in OpenBC that computes the potential

https://github.com/AMReX-Codes/amrex/blob/6c8122d437f9210e05857e4590717de1e87ad50e/Src/LinearSolvers/OpenBC/AMReX_OpenBC.cpp#L725

Is this what we'd call? Or, is OpenBC only for boundary conditions for the linear solver, and I should look into MLMG?

**Comment by BenWibking** [comment]
This line:
https://github.com/quokka-astro/quokka/blob/1b5d55dc15b46b56cc4722543230db32aa42c97f/src/simulation.hpp#L829

computes the potential and stores it in the `phi` multifabs (one for each level). Computation-wise, there's nothing to do beyond the code that already exists. Code structure-wise, `phi` just needs to be recomputed (e.g., by refactoring this into a function that returns `phi`) and saved as an extra var in the plotfiles.

**Comment by psharda** [comment]
We should make this a derived_var right, and define the function that will calculate it in the .cpp file of the test problem?

**Comment by BenWibking** [comment]
> We should make this a derived_var right, and define the function that will calculate it in the .cpp file of the test problem?

Yeah, I think that's the easiest way to do it.

**Comment by psharda** [comment]
Attempted in #406
