### ISSUE TITLE
ensure consistent first-order flux correction at box boundaries

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#374]
If a bad cell is adjacent to a box boundary, then the cell on the adjacent box on the other side of the boundary needs to have its flux updated. Currently, this does not happen, which is inconsistent.

**Comment by markkrumholz** [comment]
Could this be the explanation for the boundary imprinting we were sometimes seeing in Aditi's runs?

**Comment by BenWibking** [comment]
It could be, but I don't know why it would only affect the 2pc runs.

**Comment by markkrumholz** [comment]
I could imagine that FoFC gets invoked a lot more in these runs than in the lower resolution runs due to the lower dissipation. In any event, we should do the experiment by re-running once this bug is fixed.

**Comment by BenWibking** [comment]
That's a good point.
