### ISSUE TITLE
Print coordinates of cells requiring flux correction

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#381]
Can we also print the (x,y,z) coordinates of cells that require flux correction, in addition to their State variable contents:

https://github.com/quokka-astro/quokka/blob/ca3f360580ba184058ac696aadeedb600e94ec72/src/RadhydroSimulation.hpp#L1027

**Comment by BenWibking** [comment]
Yes, but you'll have to implement this. You can do this using the index and the cell size array from the `geom[lev]` object.

**Comment by psharda** [comment]
Closed by #383
