### ISSUE TITLE
handle VODE integration failures better

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#386]
We should do this: https://github.com/AMReX-Astro/Castro/issues/2515

cc @psharda

**Comment by psharda** [comment]
Are you saying we should check `state.error_code` after burn ?

**Comment by BenWibking** [comment]
> Are you saying we should check `state.error_code` after burn ?

Yes, we should.

If it's not being checked at all in the current code, then that would explain why we get some NaNs...

**Comment by BenWibking** [comment]
We need to have something like this:
https://github.com/AMReX-Astro/Castro/blob/f6adf9d801a03191b0b9d04678f358434c48e2b1/Source/reactions/Castro_react.cpp#L331

For Quokka, it will be _slightly_ different, since when we do reactions, we directly update the state, rather than storing the source term in its own MultiFab. But the basic idea of checking `state.error_code` for each `burn_t` and then doing a GPU reduction over this, and then an MPI reduction should be the same.

**Comment by BenWibking** [comment]
For cooling, we check for a failure by saving the number of substeps it took in each cell in its own MultiFab, performing an MPI reduction, and then checking if the maximum number of substeps is greater than or equal to the maximum allowed number of substeps:
https://github.com/quokka-astro/quokka/blob/a3fc85cc318b1738cfb42431546cf167fe4848a9/src/CloudyCooling.hpp#L277

This could also be done equally well with a boolean type MultiFab, where each cell is just `true` or `false`.

The separate MultiFab is also not strictly necessary (and it is somewhat wasteful of memory), but it makes the reduction simpler to code, since it's just one line:

https://github.com/quokka-astro/quokka/blob/a3fc85cc318b1738cfb42431546cf167fe4848a9/src/CloudyCooling.hpp#L297

**Comment by psharda** [comment]
Currently, we do:

```
if (!chemstate.success) {
	amrex::Abort("VODE integration was unsuccessful!");
}
```

**Comment by psharda** [comment]
@BenWibking so we don't need to do anything else for this right? Should we then close this issue?

**Comment by BenWibking** [comment]
Well, if it always succeeds, then no. It's impressive that it always works.

**Comment by BenWibking** [comment]
Not needed, so closing this for now.
