### ISSUE TITLE
do charge conservation normalization in a network-independent way

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#397]
Since the electron abundance normalization depends on the charge of all of the species, it should be moved into the network-specific files in Microphysics, or somehow re-written so it does not assume the species and their charges, as it does currently:

https://github.com/quokka-astro/quokka/blob/033e4f3e98b20243922d1e4407a62209f8282cee/src/Chemistry.hpp#L104

**Comment by psharda** [comment]
I think this is better done in Quokka rather than Microphysics.

**Comment by BenWibking** [comment]
> I think this is better done in Quokka rather than Microphysics.

Ok. Is there a way to have it compute what the normalization should be in a way that works for any network?

**Comment by psharda** [comment]
yeah, we can store the charge of each particle in an array that the user can fill in the input file?

**Comment by BenWibking** [comment]
@psharda you do this now, right? If so, I'll close this issue.

**Comment by psharda** [comment]
yes, its done in microphysics via https://github.com/AMReX-Astro/Microphysics/pull/1646
