### ISSUE TITLE
EnforceLimits is sometimes called with rho = 0, resulting in NANs

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#401]
Sometimes, during regridding, the function `EnforceLimits` https://github.com/quokka-astro/quokka/blob/a37934f74c6de738321d6898906afd4a054f26bd/src/hydro_system.hpp#L703 is called with rho = 0, which then leads to NANs in the velocities, energies and pressures. I traced back the call to `EnforceLimits` to this line in `FixupState`: https://github.com/quokka-astro/quokka/blob/a37934f74c6de738321d6898906afd4a054f26bd/src/RadhydroSimulation.hpp#L709, which is in turn called by https://github.com/quokka-astro/quokka/blob/a37934f74c6de738321d6898906afd4a054f26bd/src/simulation.hpp#L969

 This seems to be occurring for ghost cells (not sure though) and doesn't seem to be fatal. But it is good to keep track of this issue in case a future simulation breaks down because of it.

**Comment by psharda** [comment]
One temporary workaround to track this issue I used is to make `EnforceLimits` return a boolean value and dump a pltfile or a chkfile when it doesn't return true.

**Comment by BenWibking** [comment]
Just to clarify, does this only happens with `state_old_cc_`, or does it also happen with `state_new_cc_`?

**Comment by psharda** [comment]
> Just to clarify, does this only happens with `state_old_cc_`, or does it also happen with `state_new_cc_`?

Only with `state_old_cc`

**Comment by BenWibking** [comment]
The answer to this problem is that it is not necessary to fix up state_old_cc at all: the old time multifab is left unfilled by the regrid machinery. This is perfectly fine, since interpolation in time *immediately following a regrid* is not done (and not needed) for the regridded levels.
