### ISSUE TITLE
rename RadhydroSimulation -> QuokkaSimulation

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#428]
**Describe the proposal**
The `RadhydroSimulation` class should be renamed `QuokkaSimulation`. This should be just a global find-and-replace in the Quokka repository.

**Describe alternatives you've considered**
The class design should also be documented, but the main issue is confusion as to which class is the "main" simulation class that does all of the physics, and that appears to be caused by the naming of the `RadhydroSimulation` class.

**Additional context**
It has been confusing for new users/developers that there are three `Simulation` classes: `AMRSimulation`, `RadhydroSimulation`, and `AdvectionSimulation`. This aims to reduce the confusion by renaming `RadhydroSimulation` to `QuokkaSimulation`, since it is the class that has all of the physics and it is the class used by all of the problem files. This proposal also reduces confusion between the `QuokkaSimulation` class and the `HydroSystem` and `RadSystem` classes.

**Comment by chongchonghe** [comment]
@BenWibking I like this idea. Do you want to make this change? I can do this if you don't mind. The plan is to rename `RadhydroSimulation` to `QuokkaSimulation` and rename `RadhydroSimulation.cpp` to `QuokkaSimulation.cpp`.

**Comment by BenWibking** [comment]
Sure, I am fine with that.

**Comment by BenWibking** [comment]
Fixed by #702.
