### ISSUE TITLE
matplotlibcpp::subplot fails to work

### ISSUE THREAD

**Issue by chongchonghe** [quokka-astro/quokka#434]
**Describe the bug**
Use of matplotlibcpp::subplot failed with `Segmentation fault: address not mapped to object at address 0x10`

**To Reproduce**
1. Choose any problem, say RadPulse, and add the following code inside ifdef HAVE_PYTHON endif:
```python
  matplotlibcpp::suptitle("My plot");
  matplotlibcpp::subplot(1, 2, 1);
  matplotlibcpp::plot({1,3,2,4});
  matplotlibcpp::subplot(1, 2, 2);
  matplotlibcpp::plot({1,3,2,4});
  matplotlibcpp::save("./test_subplot.pdf");
```
3. Run this problem

[gadi-login-04:3765402:0:3765402] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)

**Additional context**
With a debugger, the error occurs at line 1463 of matplotlibcpp.h

Have you ever successfully used matplotlibcpp::subplot? Is this error due to an older version of matplotlibcpp that does not support subplot? Maybe we can consider merging in newer version of [matplotlib-cpp](https://github.com/lava/matplotlib-cpp).

**Comment by BenWibking** [comment]
This should be an issue for the matplotlib-cpp repository, not Quokka. Unfortunately, matplotlib-cpp is not maintained anymore.

For Quokka, I think a better long-term solution is to use pybind11 to call matplotlib instead: https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#executing-python-code

**Comment by chongchonghe** [comment]
I have also considered calling command line scripts from C++. We can write a script plot.py and call it in C++ script with arguments. The simulation data shall be written to disk and read by the python script. For complex figures we can write scripts for specific test problems.

**Comment by BenWibking** [comment]
It can be done even without writing the data to disk: https://github.com/quokka-astro/quokka/issues/408

**Comment by BenWibking** [comment]
Since this is an issue with matplotlibcpp, not an issue with Quokka itself, I am going to close this issue for now. If needed, you can open another issue for replacing matplotlibcpp with Python scripts.
