### ISSUE TITLE
On the convergence criteria of Newton-Raphson iteration

### ISSUE THREAD

**Issue by chongchonghe** [quokka-astro/quokka#451]
I found the following scenario where the convergence criteria for the  Newton-Raphson iteration, i.e. | F_G / E_tot | < epsilon = 1e-10, could fail. 

Imagine a test problem with matter and radiation in equilibrium with temperature T. Let's calculate how the radiation-matter exchange would work. We have $R = c \Delta t ~ \rho \kappa ~ (4 \pi B / c - E_r) = \frac{c \Delta t}{l} (a_r T^4 - E_r) $, where $l$ is the mean free path. In the diffusion regime with very high optical depth, $c \Delta t / l \gg 1$, let's say, it's 1e5. In the first iteration, the guessed value is the same as the original value, so $F_G = R$. Assume $E_r >> E_g$, then $E_{\rm tot} \approx E_r$. Then, $F_G / E_{\rm tot} = R / E_r = 10^5 (a_r T^4 / E_r - 1)$. Ideally, the part in the parathesis should be 0 since we assumed equilibrium in the beginning, but due to machine accuracy/roundoff error, it might be $\sim 10^{-14}$, then we get $F_G / E_{\rm tot} \approx 10^{-9}$. Therefore, the iteration won't break if we set epsilon to 1e-10. What I observed is that the iteration would bounce back and forth between 1e-9 and -1e-9 and never converge. 

Simply increasing epsilon won't solve the problem because the optical depth could go higher. 

@BenWibking @markkrumholz Is this a known issue? I have some idea but haven't tested it yet. I may update on this later after hearing your thoughts.

**Comment by chongchonghe** [comment]
I tried adding an extra break condition: `(a_r T^4 - E_r) / (a_r T^4) < 1e-10`. Now the issue mentioned above is avoided, but it still failed at the wave front where there is a sharp change in temperature. What happened is the calculated d Erad (Eq. 34 of the Quokka paper) is minuscule: d Erad / Erad < 1e-14, so it never converges. The test problem I'm working on has an initial temperature distribution of a top-hat function: T = 1 keV if |x| < 1 else 0. Initially, matter and radiation are in equilibrium and the density is uniform.

**Comment by BenWibking** [comment]
That's interesting. I've encountered problems with convergence stalls like this, but I didn't figure out why it was happening.

You should be able to see it with some of the existing tests if you reduce epsilon to 1e-12 or 1e-13.

It might be possible to fix this by switching to an asymptotic expansion for the full expression in the high optical depth limit. That should reduce the round off error.

**Comment by BenWibking** [comment]
It might also be worth recompiling with FPChecker to make sure there isn't a severe loss of numerical precision somewhere in the matter-energy exchange: https://fpchecker.org/

This is most likely due to a near-cancellation of the terms in the parentheses, which can cause a severe loss of numerical precision. See here for why this happens: https://fpchecker.org/2021-07-12-dealing-with-cancellation.html
