### ISSUE TITLE
implement CPU-based raytracing for direct radiation from sink particles

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#524]
**Describe the proposal**
We can do raytracing on the CPU in order to compute the effects of direct radiation from sink particles, following the HARM^2 implementation: https://ui.adsabs.harvard.edu/abs/2017JCoPh.330..924R/abstract.

**Describe alternatives you've considered**
We could instead use M1 for direct/first-collided radiation, but it is badly inaccurate when there are multiple point sources.

**Additional context**
With integrated CPU-GPU hardware platforms such as Grace Hopper, it is efficient to access data from GPU memory directly from the CPU. This makes sense for latency-bound workloads with limited parallelism, such as raytracing from point sources.

(For details, see: https://resources.nvidia.com/en-us-grace-cpu/nvidia-grace-hopper.)

**Comment by markkrumholz** [comment]
This could be useful, but it's important to understand the limitations of the algorithm. The HARM^2 implementation is fine for relatively small numbers of particles (say <~ 10), which was the case Anna Rosen and I developed it form, but it quickly became too expensive to use once the number of radiating particles became significantly greater. So the one case I could see for this is doing a small cluster and doing direct ray-tracing only for massive stars. I think for anything bigger it probably has to be M1, or we need to implement some sort of VET.

**Comment by BenWibking** [comment]
> This could be useful, but it's important to understand the limitations of the algorithm. The HARM^2 implementation is fine for relatively small numbers of particles (say <~ 10), which was the case Anna Rosen and I developed it form, but it quickly became too expensive to use once the number of radiating particles became significantly greater. So the one case I could see for this is doing a small cluster and doing direct ray-tracing only for massive stars. I think for anything bigger it probably has to be M1, or we need to implement some sort of VET.

Ok, that's fair. Our original plan from 2019 was to do M1 diffuse radiation on GPU + HARM^2 direct radiation on CPU, so I want to follow this through.

**Comment by BenWibking** [comment]
The CPU-GPU transfer cost is still quite high on Grace Hopper, so this may not be a viable method. Closing for now.
