### ISSUE TITLE
A new source term that includes the work term

### ISSUE THREAD

**Issue by chongchonghe** [quokka-astro/quokka#550]
@markkrumholz @BenWibking 

Here I describe a new scheme I developed that includes the work term in the source function. 

The reason why I want to do this is the following. The third equation in the RHD equations look like this:

$$
\frac{\partial}{\partial t} E + \nabla \cdot [(E+P)v] = c G^0
$$

Here, E is the gas **total** energy, and the fully relativistic expression of the time-like component of the four-force is (there are extra terms if $\kappa_F \ne \kappa_E$):

$$
-cG^0 = \hat{c} \gamma (\kappa_P B - \kappa_E E_r) + \hat{c} c^{-2} \gamma_3 \kappa_F v_i F_i
$$ 

Here I denote $4 \pi B/c$ as $B$. In the scheme you wrote in the Quokka paper, only the $B-E$ term is included in the source function, therefore it's okay to assume the $E$ in the above RHD equation is the internal energy. However, this simplification breaks down when you have matter and radiation (with energy density $E_0$) in thermal equilibrium in the comoving frame but not in equilibrium in the lab frame. Imagine a test problem where the radiation is in thermal equilibrium with a uniform medium and you boost it to a moving frame with velocity $v$. In the lab frame, $B = E_0$ but $E_r > E_0$ due to Lorentz transformation. Therefore, in our numerical scheme the source function is non-zero and the radiation and matter is out of equilibrium, whereas in reality they should be in equilibrium. Note that the gas internal energy/temperature is not touched in the rest of the steps where you add the work term, so it's off from the correct equilibrium forever. If you include the work term ($v_i F_i$) in the source function, one can show that the source function vanishes precisely. In this case, $E$ should be the total energy of the gas.

However, the problem is the work term is lagged because the $v$ and $F$ in the source function is lagged. This could cause big error when there is a sharp change in velocity or radiation flux. Actually, it would fail the radhydro_shock test and the radhydro_pulse test. One solution is is do an iteration on the whole "energy exchange + flux update + balance work term" routine. In this iteration, only the work term $(v F)^{\star}$ in the source function keeps updating and everything else just repeats. The iteration should break when the updated work term, $(v F)^{(n+1)}$ is close to the lagged work term $(v F)^{\star}$. While I'm working on implementing this, I want to describe another simpler solution.

A simple solution is to compensate this lagged work term with the updated work term. This is exactly the scheme I showed to Mark on Wednesday. Here are the steps:

1. Use the new source function with the lagged work term to update the gas *internal* energy $E_g$ and radiation energy $E_r$. Calculate the lagged work term: $W^* \sim v F \Delta t$. Note that I use internal energy here for convenience. Later I'll add the work term back into $E_g$.
2. Update flux
3. Update gas momentum following $(\rho v)^{(t+1)} = (\rho v)^{*} - \Delta F / (c \hat{c})$. Calculate the change in kinetic energy $\Delta K$. 
4. Add the work term back to internal energy: $E_g^{(t+1)} \leftarrow E_g^{(t+1)} + W^*$ 
5. Insure total energy conservation: $E_{r}^{(t+1)} \leftarrow E_{r}^{(t+1)} - \Delta K - W^*$. In the limit of $\Delta t \rightarrow 0$, the last two terms on the right should cancel out and the total gas energy is conserved in step 3 and step 4. 

This should solve the lagged work term problem. Indeed, this scheme passes all the current tests without introducing any more error, although it does nothing to the instability problem of the non-advecting pulse test.

One last word. It's actually not impossible to solve the following set of equations by a single Newton-Raphson iteration. 

$$
\begin{align}
\frac{\partial}{\partial t} E_g = cG^0, \\
\frac{\partial}{\partial t} E_i = -cG_i^0, \\
\frac{\partial}{\partial t} \rho v^j = G^j, \\
\frac{\partial}{\partial t} F_i^j = -\hat{c} c G_i^j, \\
\end{align}
$$

where $-\hat{c} G_0 = \hat{c} \gamma (\kappa_P B - \kappa_E E) + \hat{c} c^{-2} \gamma_3 \kappa_F v_i F_i$ and $-c \hat{c} G_i = - \hat{c} \kappa_F \gamma_2 ~F_i + \hat{c} \kappa_P B \gamma_3 ~v_i + \hat{c} \kappa_F \gamma_3 ~v_j P_{ji}$. 

The Jacobian would be a $4N + 4$ by $4N + 4$ matrix, where N is the number of photon bins. I have written down all the elements of the Jacobian. The matrix is not mostly empty, so it has to be solved via a brute force method. I won't start coding this madness unless absolutely necessary.

**Comment by chongchonghe** [comment]
Here is the branch that implements this: https://github.com/quokka-astro/quokka/tree/chongchong/new-source-term

**Comment by BenWibking** [comment]
In a non-relativistic hydro code, in practice, some terms will always have to be lagged or operator split.

Is there a test problem where you can demonstrate that the current scheme gives an unacceptable solution?

**Comment by BenWibking** [comment]
Aside: I renamed this issue to be "A new source term" in order to avoid confusion. The term "source function" in the radiation transport literature almost always refers to $B$, rather than the source terms of the hyperbolic system.

**Comment by chongchonghe** [comment]
> In a non-relativistic hydro code, in practice, some terms will always have to be lagged or operator split.
> 
> Is there a test problem where you can demonstrate that the current scheme gives an unacceptable solution?

This new source term only improves the accuracy of the code at (near) relativistic case, by a factor of $\beta^2$. Imagine a test problem where the radiation is in thermal equilibrium with a uniform medium at rest frame. Then, we boost it to a moving frame with velocity $v$. In the lab frame, $B = E_0$ but $E_r = E_0 (1 + \beta^2 / 2) > E_0$. Therefore, in the old scheme, the source term is non-zero and the radiation and matter is out of equilibrium. In the steps following the energy exchange step, the gas internal energy is not touched, so the system is away from the correct equilibrium forever. This is the test that the current scheme will fail, causing an error of $\beta^2$, which could be significant when, say, $\beta = 10^{-3}$. 

The new source term would always vanish as long as the gas the radiation is in thermal equilibrium, therefore giving the correct result to this test problem up to machine accuracy. The physics behind it is this. In the moving frame, the radiation is out of equilibrium with the thermal radiation, but the excess of radiation energy with respect to thermal emission is balanced by the work done to the radiation.

**Comment by chongchonghe** [comment]
Here is the source term iteration scheme I mentioned above. The code is in this branch: [new-source-term-iteration](https://github.com/quokka-astro/quokka/tree/chongchong/new-source-term-iteration) 

1. Use the new source term, $S = \Delta t \hat{c} \gamma (\kappa_{P} B - \kappa_E E) + \Delta t \hat{c} c^{-2} \gamma \kappa_F v_i F_i$, to update the gas internal energy $E_g$ and radiation energy $E_r$. Note that this source term includes all the terms in the time-like component of the four-force. In this step, the total energy is conserved. We record the (lagged) work term as $W^\star \sim v_i F_i$. 
2. Update flux using backward Euler scheme which include all the terms from the space-like component of the four-force: $dF_i/dt = - \hat{c} \kappa_F \gamma ~F_i + \hat{c} \kappa_P B \gamma ~v_i + \hat{c} \kappa_F \gamma ~v_j P_{ji}$ 
3. Update gas momentum following $(\rho v_i)^{(t+1)} = (\rho v_i)^{\star} - \Delta F_i / (c \hat{c})$. 
4. $E_g^{(t+1)} \leftarrow E_g^{(t+1)} - \Delta K$ where $\Delta K$ is the change in kinetic energy. In this and previous step, the gas total energy is conserved. 
5. Calculate the updated work term: $W \sim v_i F_i$. 
6. Check if $W$ converges to $W^\star$ with the criteria listed below. If yes, break; otherwise, restart from step 1 with $W^\star \leftarrow W$. The convergence criteria I use are: $(c/\hat{c}) |W - W^{\star}|/E_{\rm tot} < 10^{-13}$, or $|W - W^{\star}|/W^{\star} < 10^{-13}$, or  $|W - W^{\star}|/S < 10^{-13}$. 

This scheme passed all the tests, and at most 5 iterations is used. The results from all the tests are nearly identical to the previous results. However, it also passed the relativistic advecting uniform gas test that the old scheme would fail at. It does not fix the instability issue, though. This instability indeed comes from the odd-even instability (in the diffusion equation, the grid i does not depend on i+1 or i-1).

**Comment by BenWibking** [comment]
Ok, this seems reasonable. However, there should be a tangible benefit demonstrated with a test problem that is in the test suite to justify the increase in code complexity. In my view, it would be necessary to code up the test problem you describe above and show that it is improved with the new scheme.

**Comment by chongchonghe** [comment]
Implemented in PR #552
