### ISSUE TITLE
handle isothermal EOS entirely within EOS.hpp

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#553]
**Describe the proposal**
Before general EOS support was added to the code, an isothermal EOS was handled as a special case whenever the pressure was needed in `HydroSystem`. Now that there is general EOS support, we should move all of the conditionals to handle `gamma = 1.0` into EOS.hpp, rather than scattered elsewhere in the code.

**Describe alternatives you've considered**
We could leave it as is, but this appears to cause problems with shock flattening for isothermal problems, since a special case to handle an isothermal EOS was never written for that.

**Additional context**
This appears to be the underlying cause (or at least one of the causes) of different results for the StarCluster problem when compiled with `hipcc` versus `gcc` on CPU (presumably since this causes a NAN to be produced in a way that is handled differently by different compilers).

cc @psharda

**Comment by chongchonghe** [comment]
Just to confirm we don't need to do anything in radiation_system.hpp, right?

**Comment by BenWibking** [comment]
> Just to confirm we don't need to do anything in radiation_system.hpp, right?

I don't think so. Currently, there is a check in RadiationSystem for whether or not to do the matter-energy exchange depending on whether gamma is 1 or not. I think that's it.

**Comment by chongchonghe** [comment]
> > Just to confirm we don't need to do anything in radiation_system.hpp, right?
> 
> I don't think so. Currently, there is a check in RadiationSystem for whether or not to do the matter-energy exchange depending on whether gamma is 1 or not. I think that's it.

Right. There is special case of ignoring matter-radiation energy exchange and some terms in the flux update. I think we need to keep doing that. That's not something you can do with EOS.

**Comment by psharda** [comment]
Patch available in #573
