### ISSUE TITLE
HLLC wavespeeds are not computed correctly if cs_tilde is imaginary

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#555]
**Describe the bug**
For some left and right states, it is possible that the Roe-average sound speed is imaginary:
https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L58

Since `std::min` behaves differently for different compilers when one argument is NAN (in particular, gcc returns a the non-NAN argument while Clang returns NAN), we have problems when using Clang-based compilers to run problems that have interfaces where the Roe average is not defined:
https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L64

A reasonable solution would be to check whether $\tilde c_s^2$ is positive, and, if not, use the arithmetic average of the left and right sound speeds.

**To Reproduce**
1. Compile the PopIII problem with an Clang-based compiler.
2. Run this problem for one timestep.
3. Print out the HLLC wavespeeds for at each interface.
4. Observe NAN values.

**Additional context**
Since the AMD GPU compiler is based on Clang, it also has this problem, and is the reason the hydro update behaves differently on AMD GPUs.

Thanks to @psharda for discovering this after a truly exceptional debugging effort.

**Comment by BenWibking** [comment]
I realized that it is probably more consistent to use the specific internal energy derived from the conserved variables here: https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L52

**Comment by psharda** [comment]
> I realized that it is probably more consistent to use the specific internal energy derived from the conserved variables here:
> 
> https://github.com/quokka-astro/quokka/blob/fcde1aa11205ed64365e42ce7e084a9964aa7e9f/src/HLLC.hpp#L52

How will you re-write `C_tilde_rho` using conserved variables

**Comment by psharda** [comment]
Partially resolved by #572
