### ISSUE TITLE
move installation instructions from README to docs

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#605]
**Describe the proposal**
Move the installation instructions from README.md to the Sphinx docs, and instead add a link to the docs in README.md.

**Describe alternatives you've considered**
Keep both, but keep them in sync (hard to do).

**Additional context**
The Sphinx docs also have installation instructions, but they got out of sync from those in README.md.

**Comment by chongchonghe** [comment]
Do you plan to do this? I can also do it now. @BenWibking

**Comment by BenWibking** [comment]
> Do you plan to do this? I can also do it now. @BenWibking

Sure, go ahead.

**Comment by chongchonghe** [comment]
Done. See #607
