### ISSUE TITLE
Add a Dockerfile for CUDA

### ISSUE THREAD

**Issue by chongchonghe** [quokka-astro/quokka#745]
**Describe the proposal**

It would be great if we can have another Dockerfile with CUDA support, so we can compile CUDA tests in Docker. Currently, I do development on my Mac and I have to pull the branch on gadi and compile with nvcc there. With Docker, it should be possible to compile CUDA tests on my Mac. 

**Describe alternatives you've considered**
Continue to compile on gadi.

**Comment by BenWibking** [comment]
You could build one on top of a base image from nvidia/cuda here: https://hub.docker.com/r/nvidia/cuda
