### ISSUE TITLE
Add a units.txt file to simulation outputs

### ISSUE THREAD

**Issue by chongchonghe** [quokka-astro/quokka#780]
**Describe the proposal**
Currently, the simulation outputs does not contain information about the variable units. The user has to read the problem.cpp file in order to know the exact unit system used. I think the ideal case should be, every simulation output should contain all the information required to post-analyse it. 

My proposal is to write a CPU function to derive the unit system from the following constants: $k_B$, $c$, and $a_R$, and save a file `units.txt` into the output folder containing the following info:

```
unit_l = ...
unit_t = ...
unit_m = ...
unit_T = ...
# for multigroup
unit_nu = ...
```

However, there is a problem that I couldn't figure out. In any problem file the following three constants are defined: `k_B, c, a_R`, and their units are `erg K-1, cm s-1, erg cm-3 K-4`. We want to solve for `unit_l, unit_t, unit_e, unit_T` from these three constants. We got four unknowns but only three equations, so the problem is undetermined. Another parameter defined by the user is `mu` (mean_molecular_weight), but we don't know the mean molecular weight in cgs units ahead of time, so we can't derive `unit_m` from that either. I must be missing something. 

@BenWibking @markkrumholz 

**Describe alternatives you've considered**
Force using cgs units, which is consistent with microphysics.

**Comment by BenWibking** [comment]
I think putting this in `metadata.yaml` is the right place for this: https://github.com/quokka-astro/quokka/pull/364

**Comment by BenWibking** [comment]
The conversion into cgs units is ambiguous up to a constant. You can see this by considering Planck units where you have $c = \hbar = k_B = G = 1$ (https://en.wikipedia.org/wiki/Natural_units#Planck_units).

In Quokka, we have defined $c$, $k_B$, and $\hbar$ (implicitly via $a_R$). This tells us that we also need to define $G$ for a full system of units.

Alternatively, you could define a reference length scale, temperature, or sound speed (in cgs units), and use that as the fourth constraint.

**Comment by BenWibking** [comment]
We can still solve the equations (without gravity) without a completely-defined system of units because the radiation hydro equations have a scaling symmetry. This is why it can be written in dimensionless form. This fact is the reason why I did *not* fully define the system of units, and only had the user specify the required physical constants.

(However, if gravity is added, there is no dimensionless form, other than that defined by $c$, $\hbar$, $k_B$, and $G$!)

Given this fact, I would suggest that we include the values of the physical constants used in `metadata.yaml` and then the user can figure out the units they want to use when post-processing.

**Comment by chongchonghe** [comment]
OK. After a quick discussion with @markkrumholz , I propose the following change to the units system. The goals are to allow the use of cooling/heating formulas in cgs units from Bate & Keto (2015), and to print the unit system (unit_l, unit_m, ...) to the metadata.yaml file. I think we shouldn't force the user to do non-trivial calculations in order to get something as basic as length/mass/time units in the outputs. 

First, we should define all four constants to complete the unit system. Given the code values of $c, a_R, k_B, G$, we can derive `unit_l, unit_m, unit_t, unit_T`. To simplify the user interface, I propose we allow the user to choose one of the three unit systems with a constexpr: `UnitSystem::cgs, UnitSystem::constants, UnitSystem::custom`. 

The `UnitSystem::constants` would be the same as the current implementation, where the user defines the values of all four constants, e.g.

```c++
Unit_Traits<problem_t> {
  static constexpr UnitSystem unit_system = UnitSystem::constants;
  static constexpr c_light = 1.0;
 	static constexpr boltzmann_constant = 1.0; 
  static constexpr radiation_constant = 1.0;
  static constexpr gravitational_constant = 1.0;
}
```

To use the cgs unit system, the user only needs to specify `unit_system = cgs` and the constants are defined at compile time. e.g. 

```c++
Unit_Traits<problem_t> {
  static constexpr UnitSystem unit_system = UnitSystem::CGS;
}
```

The third option is to define a custom unit system by specifying the unit of length, time, etc, and the constants are derived from them at compile time. e.g. 

```c++
Unit_Traits<problem_t> {
  static constexpr UnitSystem unit_system = UnitSystem::custom;
  static constexpr unit_l = 3.085677581e+18; // cm
 	static constexpr unit_m = 1.988409871e+33; // g
  static constexpr unit_t = 3.15576e+07; // s
  static constexpr unit_T = 1.0e+05; // K
}
```

This gives the user flexibility to use arbitrary unit systems and also allows the test problems to use dimensionless unit systems. 

I'm going to code this and create a PR. @BenWibking please let me know what you think.

**Comment by BenWibking** [comment]
This sounds like a nice solution. Keep in mind that OpenPMD has its own way of handling units in the output files and that should be updated as well.

There is one complication in handling the electromagnetic units, which will be needed when adding MHD. Usually MHD codes use the Heaviside-Lorentz system of units, which is cgs _except_ for the electric and magnetic field units, which differ by a factor of 1/sqrt(4pi). This is equivalent to setting epsilon = mu = 1. So this solution is fine for now, but we need to come back and add the permittivity and permeability, which are assumed to be 1 in the MHD solver.

**Comment by BenWibking** [comment]
Also- the cooling modules currently assume that the simulation units are cgs, so we should add a runtime check that that is the case if cooling is turned on at runtime.

**Comment by chongchonghe** [comment]
The point of making this change is to enable us to use cooling formulas with arbitrary unit system, both CGS or CUSTOM. I'll add an `static_assert` to make sure CGS is used when the cooling modules are enabled. In the future, I'll try to make the cooling modules compatible with CUSTOM unit system as well.
